# UNISYM for GCC-Lin32 built-2024-03-24 00:14:40.243156

CC32 = gcc -m32
CX32 = g++ -m32
CC64 = gcc -m64
CX64 = g++ -m64
AASM = /mnt/hgfs/_bin/ELF64/aasm
attr = -D_DEBUG -D_Linux -O3
aattr = -felf -I$(udir)/inc/Kasha/n_
udir = /mnt/hgfs/unisym
dest_obj=~/_obj/CGLin32
.PHONY: all

all:
	-@mkdir -p ${dest_obj}
	-@rm -f ${dest_obj}/*
	cd ${dest_obj}/ && $(AASM) $(aattr) $(udir)/lib/asm/x86/cpuid.asm  -o./cpuid.a.o
	cd ${dest_obj}/ && $(AASM) $(aattr) $(udir)/lib/asm/x86/binary.asm -o./binary.a.o
	$(CC32) -c ./lib/c/binary.c -o ${dest_obj}/_ugc32_binary.o $(attr)
	$(CC32) -c ./lib/c/consio.c -o ${dest_obj}/_ugc32_consio.o $(attr)
	$(CC32) -c ./lib/c/contable.c -o ${dest_obj}/_ugc32_contable.o $(attr)
	$(CC32) -c ./lib/c/crc64.c -o ${dest_obj}/_ugc32_crc64.o $(attr)
	$(CC32) -c ./lib/c/debug.c -o ${dest_obj}/_ugc32_debug.o $(attr)
	$(CC32) -c ./lib/c/error.c -o ${dest_obj}/_ugc32_error.o $(attr)
	$(CC32) -c ./lib/c/mcore.c -o ${dest_obj}/_ugc32_mcore.o $(attr)
	$(CC32) -c ./lib/c/numar.c -o ${dest_obj}/_ugc32_numar.o $(attr)
	$(CC32) -c ./lib/c/regar.c -o ${dest_obj}/_ugc32_regar.o $(attr)
	$(CC32) -c ./lib/c/stack.c -o ${dest_obj}/_ugc32_stack.o $(attr)
	$(CC32) -c ./lib/c/strpool.c -o ${dest_obj}/_ugc32_strpool.o $(attr)
	$(CC32) -c ./lib/c/tenar.c -o ${dest_obj}/_ugc32_tenar.o $(attr)
	$(CC32) -c ./lib/c/window.c -o ${dest_obj}/_ugc32_window.o $(attr)
	$(CC32) -c ./lib/c/auxiliary/toxxxer.c -o ${dest_obj}/_ugc32_toxxxer.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeAcos.c -o ${dest_obj}/_ugc32_CoeAcos.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeAcosh.c -o ${dest_obj}/_ugc32_CoeAcosh.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeAdd.c -o ${dest_obj}/_ugc32_CoeAdd.o $(attr)
	$(CC32) -c ./lib/c/coear/coear.c -o ${dest_obj}/_ugc32_coear.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeAsin.c -o ${dest_obj}/_ugc32_CoeAsin.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeAsinh.c -o ${dest_obj}/_ugc32_CoeAsinh.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeAtan.c -o ${dest_obj}/_ugc32_CoeAtan.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeAtanh.c -o ${dest_obj}/_ugc32_CoeAtanh.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeCmp.c -o ${dest_obj}/_ugc32_CoeCmp.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeCos.c -o ${dest_obj}/_ugc32_CoeCos.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeCosh.c -o ${dest_obj}/_ugc32_CoeCosh.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeCpy.c -o ${dest_obj}/_ugc32_CoeCpy.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeCtz.c -o ${dest_obj}/_ugc32_CoeCtz.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeDel.c -o ${dest_obj}/_ugc32_CoeDel.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeDig.c -o ${dest_obj}/_ugc32_CoeDig.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeDiv.c -o ${dest_obj}/_ugc32_CoeDiv.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeDivrAlign.c -o ${dest_obj}/_ugc32_CoeDivrAlign.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeDivrUnit.c -o ${dest_obj}/_ugc32_CoeDivrUnit.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeE.c -o ${dest_obj}/_ugc32_CoeE.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeExp.c -o ${dest_obj}/_ugc32_CoeExp.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeExpoAlign.c -o ${dest_obj}/_ugc32_CoeExpoAlign.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeFac.c -o ${dest_obj}/_ugc32_CoeFac.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeFromDouble.c -o ${dest_obj}/_ugc32_CoeFromDouble.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeFromInteger.c -o ${dest_obj}/_ugc32_CoeFromInteger.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeFromLocale.c -o ${dest_obj}/_ugc32_CoeFromLocale.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeHypot.c -o ${dest_obj}/_ugc32_CoeHypot.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeInit.c -o ${dest_obj}/_ugc32_CoeInit.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeInt.c -o ${dest_obj}/_ugc32_CoeInt.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeIsINF.c -o ${dest_obj}/_ugc32_CoeIsINF.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeIsNAN.c -o ${dest_obj}/_ugc32_CoeIsNAN.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeLog.c -o ${dest_obj}/_ugc32_CoeLog.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeMul.c -o ${dest_obj}/_ugc32_CoeMul.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeNeg.c -o ${dest_obj}/_ugc32_CoeNeg.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeNew.c -o ${dest_obj}/_ugc32_CoeNew.o $(attr)
	$(CC32) -c ./lib/c/coear/CoePi.c -o ${dest_obj}/_ugc32_CoePi.o $(attr)
	$(CC32) -c ./lib/c/coear/CoePow.c -o ${dest_obj}/_ugc32_CoePow.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeRst.c -o ${dest_obj}/_ugc32_CoeRst.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeSgn.c -o ${dest_obj}/_ugc32_CoeSgn.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeSin.c -o ${dest_obj}/_ugc32_CoeSin.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeSinh.c -o ${dest_obj}/_ugc32_CoeSinh.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeSqrt.c -o ${dest_obj}/_ugc32_CoeSqrt.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeSquare.c -o ${dest_obj}/_ugc32_CoeSquare.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeSub.c -o ${dest_obj}/_ugc32_CoeSub.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeTan.c -o ${dest_obj}/_ugc32_CoeTan.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeTanh.c -o ${dest_obj}/_ugc32_CoeTanh.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeTaylor.c -o ${dest_obj}/_ugc32_CoeTaylor.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeToDouble.c -o ${dest_obj}/_ugc32_CoeToDouble.o $(attr)
	$(CC32) -c ./lib/c/coear/CoeToLocale.c -o ${dest_obj}/_ugc32_CoeToLocale.o $(attr)
	$(CC32) -c ./lib/c/datime/fromherp.c -o ${dest_obj}/_ugc32_fromherp.o $(attr)
	$(CC32) -c ./lib/c/datime/POSIXGetSeconds.c -o ${dest_obj}/_ugc32_POSIXGetSeconds.o $(attr)
	$(CC32) -c ./lib/c/datime/weekday.c -o ${dest_obj}/_ugc32_weekday.o $(attr)
	$(CC32) -c ./lib/c/dnode/dnode.c -o ${dest_obj}/_ugc32_dnode.o $(attr)
	$(CC32) -c ./lib/c/dnode/DnodeAppend.c -o ${dest_obj}/_ugc32_DnodeAppend.o $(attr)
	$(CC32) -c ./lib/c/dnode/DnodeBind.c -o ${dest_obj}/_ugc32_DnodeBind.o $(attr)
	$(CC32) -c ./lib/c/dnode/DnodeCount.c -o ${dest_obj}/_ugc32_DnodeCount.o $(attr)
	$(CC32) -c ./lib/c/dnode/DnodeIndex.c -o ${dest_obj}/_ugc32_DnodeIndex.o $(attr)
	$(CC32) -c ./lib/c/dnode/DnodeInsert.c -o ${dest_obj}/_ugc32_DnodeInsert.o $(attr)
	$(CC32) -c ./lib/c/dnode/DnodeRelease.c -o ${dest_obj}/_ugc32_DnodeRelease.o $(attr)
	$(CC32) -c ./lib/c/dnode/DnodeRemove.c -o ${dest_obj}/_ugc32_DnodeRemove.o $(attr)
	$(CC32) -c ./lib/c/dnode/DnodeRewind.c -o ${dest_obj}/_ugc32_DnodeRewind.o $(attr)
	$(CC32) -c ./lib/c/dnode/DnodeSort.c -o ${dest_obj}/_ugc32_DnodeSort.o $(attr)
	$(CC32) -c ./lib/c/inode/InodeDelete.c -o ${dest_obj}/_ugc32_InodeDelete.o $(attr)
	$(CC32) -c ./lib/c/inode/InodeLocate.c -o ${dest_obj}/_ugc32_InodeLocate.o $(attr)
	$(CC32) -c ./lib/c/inode/InodesRelease.c -o ${dest_obj}/_ugc32_InodesRelease.o $(attr)
	$(CC32) -c ./lib/c/inode/InodeUpdate.c -o ${dest_obj}/_ugc32_InodeUpdate.o $(attr)
	$(CC32) -c ./lib/c/nnode/nnode.c -o ${dest_obj}/_ugc32_nnode.o $(attr)
	$(CC32) -c ./lib/c/nnode/NnodeBlock.c -o ${dest_obj}/_ugc32_NnodeBlock.o $(attr)
	$(CC32) -c ./lib/c/nnode/NnodeInsert.c -o ${dest_obj}/_ugc32_NnodeInsert.o $(attr)
	$(CC32) -c ./lib/c/nnode/NnodeRelease.c -o ${dest_obj}/_ugc32_NnodeRelease.o $(attr)
	$(CC32) -c ./lib/c/nnode/NnodesRelease.c -o ${dest_obj}/_ugc32_NnodesRelease.o $(attr)
	$(CC32) -c ./lib/c/node/node.c -o ${dest_obj}/_ugc32_node.o $(attr)
	$(CC32) -c ./lib/c/node/NodeAppend.c -o ${dest_obj}/_ugc32_NodeAppend.o $(attr)
	$(CC32) -c ./lib/c/node/NodeCount.c -o ${dest_obj}/_ugc32_NodeCount.o $(attr)
	$(CC32) -c ./lib/c/node/NodeIndex.c -o ${dest_obj}/_ugc32_NodeIndex.o $(attr)
	$(CC32) -c ./lib/c/node/NodeInsert.c -o ${dest_obj}/_ugc32_NodeInsert.o $(attr)
	$(CC32) -c ./lib/c/node/NodeRelease.c -o ${dest_obj}/_ugc32_NodeRelease.o $(attr)
	$(CC32) -c ./lib/c/node/NodeRemove.c -o ${dest_obj}/_ugc32_NodeRemove.o $(attr)
	$(CC32) -c ./lib/c/node/NodeSort.c -o ${dest_obj}/_ugc32_NodeSort.o $(attr)
	$(CC32) -c ./lib/c/tnode/StrTokenAll.c -o ${dest_obj}/_ugc32_StrTokenAll.o $(attr)
	$(CC32) -c ./lib/c/tnode/StrTokenAppend.c -o ${dest_obj}/_ugc32_StrTokenAppend.o $(attr)
	$(CC32) -c ./lib/c/tnode/StrTokenClearAll.c -o ${dest_obj}/_ugc32_StrTokenClearAll.o $(attr)
	$(CC32) -c ./lib/c/tnode/StrTokenThrow.c -o ${dest_obj}/_ugc32_StrTokenThrow.o $(attr)
	$(CC32) -c ./lib/c/tnode/tnode.c -o ${dest_obj}/_ugc32_tnode.o $(attr)
	$(CC32) -c ./lib/c/tnode/TnodesReleases.c -o ${dest_obj}/_ugc32_TnodesReleases.o $(attr)
	$(CC32) -c ./lib/c/ustring/astring/atobcd.c -o ${dest_obj}/_ugc32_atobcd.o $(attr)
	$(CC32) -c ./lib/c/ustring/astring/bcdtoa.c -o ${dest_obj}/_ugc32_bcdtoa.o $(attr)
	$(CC32) -c ./lib/c/ustring/astring/instoa.c -o ${dest_obj}/_ugc32_instoa.o $(attr)
	$(CC32) -c ./lib/c/ustring/astring/MemHeap.c -o ${dest_obj}/_ugc32_MemHeap.o $(attr)
	$(CC32) -c ./lib/c/ustring/astring/StrHeap.c -o ${dest_obj}/_ugc32_StrHeap.o $(attr)
	$(CC32) -c ./lib/c/ustring/astring/StrHeapAppend.c -o ${dest_obj}/_ugc32_StrHeapAppend.o $(attr)
	$(CC32) -c ./lib/c/ustring/astring/StrHeapAppendChars.c -o ${dest_obj}/_ugc32_StrHeapAppendChars.o $(attr)
	$(CC32) -c ./lib/c/ustring/astring/StrHeapAppendN.c -o ${dest_obj}/_ugc32_StrHeapAppendN.o $(attr)
	$(CC32) -c ./lib/c/ustring/astring/StrHeapFromChar.c -o ${dest_obj}/_ugc32_StrHeapFromChar.o $(attr)
	$(CC32) -c ./lib/c/ustring/astring/StrHeapInsertThrow.c -o ${dest_obj}/_ugc32_StrHeapInsertThrow.o $(attr)
	$(CC32) -c ./lib/c/ustring/astring/StrHeapN.c -o ${dest_obj}/_ugc32_StrHeapN.o $(attr)
	$(CC32) -c ./lib/c/ustring/astring/StrReplace.c -o ${dest_obj}/_ugc32_StrReplace.o $(attr)
	$(CC32) -c ./lib/c/ustring/chrar/ChrAdd.c -o ${dest_obj}/_ugc32_ChrAdd.o $(attr)
	$(CC32) -c ./lib/c/ustring/chrar/ChrArrange.c -o ${dest_obj}/_ugc32_ChrArrange.o $(attr)
	$(CC32) -c ./lib/c/ustring/chrar/ChrCmp.c -o ${dest_obj}/_ugc32_ChrCmp.o $(attr)
	$(CC32) -c ./lib/c/ustring/chrar/ChrCombinate.c -o ${dest_obj}/_ugc32_ChrCombinate.o $(attr)
	$(CC32) -c ./lib/c/ustring/chrar/ChrComDiv.c -o ${dest_obj}/_ugc32_ChrComDiv.o $(attr)
	$(CC32) -c ./lib/c/ustring/chrar/ChrComMul.c -o ${dest_obj}/_ugc32_ChrComMul.o $(attr)
	$(CC32) -c ./lib/c/ustring/chrar/ChrCpz.c -o ${dest_obj}/_ugc32_ChrCpz.o $(attr)
	$(CC32) -c ./lib/c/ustring/chrar/ChrCtz.c -o ${dest_obj}/_ugc32_ChrCtz.o $(attr)
	$(CC32) -c ./lib/c/ustring/chrar/ChrDecToHex.c -o ${dest_obj}/_ugc32_ChrDecToHex.o $(attr)
	$(CC32) -c ./lib/c/ustring/chrar/ChrDecToHexFloat.c -o ${dest_obj}/_ugc32_ChrDecToHexFloat.o $(attr)
	$(CC32) -c ./lib/c/ustring/chrar/ChrDiv.c -o ${dest_obj}/_ugc32_ChrDiv.o $(attr)
	$(CC32) -c ./lib/c/ustring/chrar/ChrFactorial.c -o ${dest_obj}/_ugc32_ChrFactorial.o $(attr)
	$(CC32) -c ./lib/c/ustring/chrar/ChrHexToDec.c -o ${dest_obj}/_ugc32_ChrHexToDec.o $(attr)
	$(CC32) -c ./lib/c/ustring/chrar/ChrHexToDecFloat.c -o ${dest_obj}/_ugc32_ChrHexToDecFloat.o $(attr)
	$(CC32) -c ./lib/c/ustring/chrar/ChrInsPow.c -o ${dest_obj}/_ugc32_ChrInsPow.o $(attr)
	$(CC32) -c ./lib/c/ustring/chrar/ChrMul.c -o ${dest_obj}/_ugc32_ChrMul.o $(attr)
	$(CC32) -c ./lib/c/ustring/chrar/ChrSub.c -o ${dest_obj}/_ugc32_ChrSub.o $(attr)
	$(CC32) -c ./lib/c/ustring/chrar/DigDec.c -o ${dest_obj}/_ugc32_DigDec.o $(attr)
	$(CC32) -c ./lib/c/ustring/chrar/DigInc.c -o ${dest_obj}/_ugc32_DigInc.o $(attr)
	$(CC32) -c ./lib/c/ustring/gstring/atoins.c -o ${dest_obj}/_ugc32_atoins.o $(attr)
	$(CC32) -c ./lib/c/ustring/gstring/instob.c -o ${dest_obj}/_ugc32_instob.o $(attr)
	$(CC32) -c ./lib/c/ustring/gstring/MemCompareRight.c -o ${dest_obj}/_ugc32_MemCompareRight.o $(attr)
	$(CC32) -c ./lib/c/ustring/gstring/MemSet.c -o ${dest_obj}/_ugc32_MemSet.o $(attr)
	$(CC32) -c ./lib/c/ustring/gstring/StrDeprefixSpaces.c -o ${dest_obj}/_ugc32_StrDeprefixSpaces.o $(attr)
	$(CC32) -c ./lib/c/ustring/gstring/StrDesuffixSpaces.c -o ${dest_obj}/_ugc32_StrDesuffixSpaces.o $(attr)
	$(CC32) -c ./lib/c/ustring/gstring/StrFilter.c -o ${dest_obj}/_ugc32_StrFilter.o $(attr)
	$(CC32) -c ./lib/c/ustring/gstring/StrFilterOut.c -o ${dest_obj}/_ugc32_StrFilterOut.o $(attr)
	$(CC32) -c ./lib/c/ustring/gstring/StrFilterOutString.c -o ${dest_obj}/_ugc32_StrFilterOutString.o $(attr)
	$(CC32) -c ./lib/c/ustring/gstring/StrFilterString.c -o ${dest_obj}/_ugc32_StrFilterString.o $(attr)
	$(CC32) -c ./lib/c/ustring/gstring/StrShiftLeft4.c -o ${dest_obj}/_ugc32_StrShiftLeft4.o $(attr)
	$(CC32) -c ./lib/c/ustring/gstring/StrShiftLeft8n.c -o ${dest_obj}/_ugc32_StrShiftLeft8n.o $(attr)
	$(CC32) -c ./lib/c/ustring/gstring/StrShiftRight4.c -o ${dest_obj}/_ugc32_StrShiftRight4.o $(attr)
	$(CC32) -c ./lib/c/ustring/gstring/StrShiftRight8n.c -o ${dest_obj}/_ugc32_StrShiftRight8n.o $(attr)
	$(CC32) -c ./lib/c/ustring/gstring/StrSortBubble.c -o ${dest_obj}/_ugc32_StrSortBubble.o $(attr)
	$(CC32) -c ./lib/c/ustring/gstring/_size_decimal_get.c -o ${dest_obj}/_ugc32__size_decimal_get.o $(attr)
	$(CX32) -c ./lib/cpp/coe.cpp -o ${dest_obj}/_uxxgc32_coe.o $(attr)
	$(CX32) -c ./lib/cpp/consio.cpp -o ${dest_obj}/_uxxgc32_consio.o $(attr)
	$(CX32) -c ./lib/cpp/floating.cpp -o ${dest_obj}/_uxxgc32_floating.o $(attr)
	$(CX32) -c ./lib/cpp/numberx.cpp -o ${dest_obj}/_uxxgc32_numberx.o $(attr)
	$(CX32) -c ./lib/cpp/strpool.cpp -o ${dest_obj}/_uxxgc32_strpool.o $(attr)
	$(CX32) -c ./lib/cpp/ustream.cpp -o ${dest_obj}/_uxxgc32_ustream.o $(attr)
	$(CX32) -c ./lib/cpp/ustring.cpp -o ${dest_obj}/_uxxgc32_ustring.o $(attr)
	$(CX32) -c ./lib/cpp/nodes/dnode.cpp -o ${dest_obj}/_uxxgc32_dnode.o $(attr)
	$(CX32) -c ./lib/cpp/nodes/inode.cpp -o ${dest_obj}/_uxxgc32_inode.o $(attr)
	$(CX32) -c ./lib/cpp/nodes/nnode.cpp -o ${dest_obj}/_uxxgc32_nnode.o $(attr)
	$(CX32) -c ./lib/cpp/nodes/node.cpp -o ${dest_obj}/_uxxgc32_node.o $(attr)
	$(CX32) -c ./lib/cpp/nodes/tnode.cpp -o ${dest_obj}/_uxxgc32_tnode.o $(attr)
	$(CX32) -c ./lib/cpp/nodes/nnode/NnodeParse.cpp -o ${dest_obj}/_uxxgc32_NnodeParse.o $(attr)
	$(CX32) -c ./lib/cpp/nodes/nnode/NnodeParse/NnodeParseOperator.cpp -o ${dest_obj}/_uxxgc32_NnodeParseOperator.o $(attr)
	$(CX32) -c ./lib/cpp/nodes/tnode/TokenParse.cpp -o ${dest_obj}/_uxxgc32_TokenParse.o $(attr)
	cd ${dest_obj}/ && ar -rcs /mnt/hgfs/_bin/libl32.a *
