// ASCII C TAB4 CRLF
// Attribute: ArnCovenant Host bins(16+) 386+
// LastCheck: RFX19
// AllAuthor: @dosconio
/*
	Copyright 2023 ArinaMgk

	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0
	http://unisym.org/license.html

	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
*/
#define _CRT_SECURE_NO_WARNINGS
#include <stdinc.h>
#include <ustdbool.h>
#include <ustring.h>
#include <stdio.h>
#include <time.h>
#include <strpage.h>
#include <strbuff.h>
#include "aasm.h"

extern time_t startup_time;

static byte rest_parse_phase = 2;
bool terminate_after_phase = false;
bool treat_warn_as_erro = false;
bool enable_warning = true;
bool endian_little = true;
bool using_debug_info = false;

#define FILENAME_MAX 260
static char inname[FILENAME_MAX];
char outname[FILENAME_MAX];
static char listname[FILENAME_MAX];
static char errname[FILENAME_MAX];

Strpage* _offsets;
Strbuff* _forwrefs;

FILE* outfile = NULL;
time_t official_compile_time;


typedef struct ForewardReference {
	int lineno;// line number
	_TEMP int operand;
} forwrefinfo;

static stduint next_seg;
stduint SegAlloc() { // seg_alloc
	return (next_seg += 2) - 2;
}

struct dfmt {
	rostr fullname;// short (one-liner) description of the type of output generated by the driver
	rostr shortname;
};
struct ofmt {
	rostr fullname;
	rostr shortname;
	unsigned flagsl;
	struct dfmt** debug_formats;// to the first element of the debug information
	struct dfmt* current_dfmt;// to the element that is being used. Set defaultly and changed by -F
	macros_t* stdmac;// NULL-terminated. to extra standard macros supplied-by object format
	// e.g. initial default value of __SECT__, and user-level equivalents for any format-specific directives

};// output format
static struct ofmt* ofmt = NULL;
struct dfmt null_debug_form = {
	"Null debug format",
	"null",
	//{} null_debug_init,
	//{} null_debug_linenum,
	//{} null_debug_deflabel,
	//{} null_debug_routine,
	//{} null_debug_typevalue,
	//{} null_debug_output,
	//{} null_debug_cleanup
};

//: Dependence

static rostr depend_target = NULL;
static rostr depend_file = NULL;
void getcrt(_Need_free char** const pname, stduint* const plineno)
{
	//{TODO}
	*plineno = 12;
	*pname = StrHeap("nihao.asm");
}

int drop();
int main(int argc, char** argv, char** envv)
{
	time(&startup_time);
	//{TODO} report_error = report_error_gnu;
	//{TODO} error_file = stderr;
	//{TODO} _set_malloc_error(report_error);
	_offsets = StrpageNew();
	_forwrefs = StrbuffNew(byteof(forwrefinfo));
	_logstyle = _LOG_STYLE_GCC;
	_call_serious = handlog;
	//{TODO} preproc = &nasmpp;
	//{TODO} operating_mode = op_normal;
	next_seg = 0;// seg_init();
	// define macros time-related
	{
		stduint tempsiz = 128;
		char* temp = malc(tempsiz);
		struct tm lt, * lt_p,
			gm, * gm_p;
		uint64 posix_time;
		if (!temp) return _TEMP -1;
		if (lt_p = localtime(&official_compile_time)) {
			lt = *lt_p;
			strftime(temp, tempsiz, "__DATE__=\"%Y-%m-%d\"", &lt);
			printl(_LOG_INFO, "%s", temp);
			//{} pp_pre_define
			strftime(temp, tempsiz, "__DATE_NUM__=%Y%m%d", &lt);
			printl(_LOG_INFO, "%s", temp);
			//{} pp_pre_define
			strftime(temp, tempsiz, "__TIME__=\"%H:%M:%S\"", &lt);
			printl(_LOG_INFO, "%s", temp);
			//{} pp_pre_define
			strftime(temp, tempsiz, "__TIME_NUM__=%H%M%S", &lt);
			printl(_LOG_INFO, "%s", temp);
			//{} pp_pre_define
		}
		if (gm_p = gmtime(&official_compile_time)) {
			gm = *gm_p;
			strftime(temp, tempsiz, "__UTC_DATE__=\"%Y-%m-%d\"", &lt);
			printl(_LOG_INFO, "%s", temp);
			//{} pp_pre_define
			strftime(temp, tempsiz, "__UTC_DATE_NUM__=%Y%m%d", &lt);
			printl(_LOG_INFO, "%s", temp);
			//{} pp_pre_define
			strftime(temp, tempsiz, "__UTC_TIME__=\"%H:%M:%S\"", &lt);
			printl(_LOG_INFO, "%s", temp);
			//{} pp_pre_define
			strftime(temp, tempsiz, "__UTC_TIME_NUM__=%H%M%S", &lt);
			printl(_LOG_INFO, "%s", temp);
			//{} pp_pre_define
		}
		posix_time = gm_p ? POSIXGetSeconds(&gm) :
			lt_p ? POSIXGetSeconds(&lt) : 0;
		if (posix_time) {
			snprintf(temp, tempsiz, "__POSIX_TIME__=%" PRId64, posix_time);
			printl(_LOG_INFO, "%s", temp);
			//{} pp_pre_define
		}
		mfree(temp);
	}
	//{TODO}  parse_cmdline(argc, argv);
	if (terminate_after_phase || !ofmt) 
		printl(_LOG_PANIC, "terminate_after_phase || ofmt");
	if (!using_debug_info)
		ofmt->current_dfmt = &null_debug_form;
	if (ofmt->stdmac)
		;//{} pp_extra_stdmac(ofmt->stdmac);
	//{} parser_global_info(ofmt, &location);
	//{} eval_global_info(ofmt, lookup_label, &location);
	//{} define_macros_late(); // define some macros dependent of command-line
	//{} depend_ptr = (depend_file || (operating_mode == op_depend))? &depend_list : NULL;
	asserz(depend_target) = outname;
	switch (_TODO 0) {
		//{TODO} ...
	default: break;
	}
	//{} if (depend_list && !terminate_after_phase) emit_dependencies(depend_list);
	return drop();
}

int drop() {
	printinfo();
	StrpageFree(_offsets);
	StrbuffFree(_forwrefs);
	//{TODO} eval_cleanup();
	//{TODO} stdscan_cleanup();
	return malc_count;
}
