
typedef struct {
	struct {
		byte Fore_B : 1;// blue
		byte Fore_G : 1;// green
		byte Fore_R : 1;// red
		byte Highlight : 1;
		byte Back_B : 1;// blue
		byte Back_G : 1;// green
		byte Back_R : 1;// red
		byte Kirablink : 1;
	};
	byte Bold;
	byte Underline;
} ConsoleCharPropertyColor8;

enum CON_FORECOLOR {
#if 0
#elif defined(_Linux) || 1 // VT100
	CON_FORE_DEFAULT = 39,
	CON_FORE_DARK = 30,
	CON_FORE_RED = 31,
	CON_FORE_GREEN = 32,
	CON_FORE_YELLOW = 33,
	CON_FORE_BLUE = 34,
	CON_FORE_MAGENTA = 35,
	CON_FORE_CYAN = 36,
	CON_FORE_GRAY = 37,
	CON_FORE_GRAY_LIGHT = 90,
	CON_FORE_RED_LIGHT = 91,
	CON_FORE_GREEN_LIGHT = 92,
	CON_FORE_YELLOW_LIGHT = 93,
	CON_FORE_BLUE_LIGHT = 94,
	CON_FORE_MAGENTA_LIGHT = 95,
	CON_FORE_CYAN_LIGHT = 96,
	CON_FORE_WHITE = 97,
#endif
};
enum CON_BACKCOLOR {
#if 0
#elif defined(_Linux) || 1 // VT100
	CON_BACK_DEFAULT = CON_FORE_DEFAULT + 10,
	CON_BACK_DARK = CON_FORE_DARK + 10,
	CON_BACK_RED = CON_FORE_RED + 10,
	CON_BACK_GREEN = CON_FORE_GREEN + 10,
	CON_BACK_YELLOW = CON_FORE_YELLOW + 10,
	CON_BACK_BLUE = CON_FORE_BLUE + 10,
	CON_BACK_MAGENTA = CON_FORE_MAGENTA + 10,
	CON_BACK_CYAN = CON_FORE_CYAN + 10,
	CON_BACK_GRAY = CON_FORE_GRAY + 10,
	CON_BACK_GRAY_LIGHT = CON_FORE_GRAY_LIGHT + 10,
	CON_BACK_RED_LIGHT = CON_FORE_RED_LIGHT + 10,
	CON_BACK_GREEN_LIGHT = CON_FORE_GREEN_LIGHT + 10,
	CON_BACK_YELLOW_LIGHT = CON_FORE_YELLOW_LIGHT + 10,
	CON_BACK_BLUE_LIGHT = CON_FORE_BLUE_LIGHT + 10,
	CON_BACK_MAGENTA_LIGHT = CON_FORE_MAGENTA_LIGHT + 10,
	CON_BACK_CYAN_LIGHT = CON_FORE_CYAN_LIGHT + 10,
	CON_BACK_WHITE = CON_FORE_WHITE + 10,
#endif
};
